name: genius_wallet
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.1
  another_flushbar: ^1.12.30
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.4
  injectable: ^2.3.0
  connectivity_plus: ^4.0.2
  flutter_svg: ^2.0.7
  avatars: ^3.0.2
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.14
  image_picker: ^1.0.4
  dropdown_search: ^5.0.6
  pull_to_refresh_flutter3: ^2.0.2
  phone_form_field:
    git:
      url: https://github.com/faisal-kabir/phone_form_field.git
      ref: dev
  timer_count_down: ^2.2.2
  pin_code_fields: ^8.0.1
  cupertino_icons: ^1.0.6
  timeago: ^3.5.0
  package_info_plus: ^4.1.0
  webview_flutter: ^4.4.1
  flutter_widget_from_html: ^0.10.5+3
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner:
  flutter_gen_runner:


  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1



flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"


flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/flags/
    - assets/icons/


  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

    - family: plex_sans
      fonts:
        - asset: fonts/plex_sans/IBMPlexSans-Light.ttf
          weight: 300
        - asset: fonts/plex_sans/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: fonts/plex_sans/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: fonts/plex_sans/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: fonts/plex_sans/IBMPlexSans-Bold.ttf
          weight: 700

